<package format="3">
  <name>dsr_cumotion_goal_interface</name>
  <version>0.0.1</version>
  <description>BT-style MoveIt2 command dispatcher (pose/joint/named)</description>
  <maintainer email="admin@example.com">admin</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>shape_msgs</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>action_msgs</exec_depend>
  <exec_depend>dsr_msgs2</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
