# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 5.0
  trajectory_duration_monitoring: false # Prevent interruptions due to timeouts

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - dsr_moveit_controller

  dsr_moveit_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  # JointTrajectoryController parameters
  action_monitor_rate: 20.0

  # 부분 목표 허용 여부
  allow_partial_joints_goal: false

  # 새로운 궤적 입력 시 마지막 명령값 기준으로 보간
  interpolate_from_desired_state: true

  # ★ 궤적 끝에서 속도가 아주 조금 남아 있어도 허용
  allow_nonzero_velocity_at_trajectory_end: true

  constraints:
    # 로봇이 '멈췄다'고 판단할 속도 허용치
    stopped_velocity_tolerance: 0.01
    # goal 도달 후 기다릴 수 있는 허용 시간 (0이면 제한 없음)
    goal_time: 0.0