objects:
  # - id: cyl1
  #   type: cylinder
  #   position: [0.55, -0.4, 0.0]
  #   dimensions: [0.05, 0.8]  # radius, height

  # - id: cyl2
  #   type: cylinder
  #   position: [0.7, 0.1, 0.0]
  #   dimensions: [0.03, 1.0]  # radius, height

  # - id: cyl3
  #   type: cylinder
  #   position: [0.4, 0.40, 0.0]
  #   dimensions: [0.04, 0.5]  # radius, height

  - id: zig_1
    type: mesh
    mesh_path: /workspaces/ros2_ws/src/cumotion/dsr_cumotion/meshes/object/zig_test2.stl
    position: [1.1, -0.8, -1.0]
    orientation: [0.0, 0.0, 0.7071068, 0.7071068]
    scale: [0.001, 0.001, 0.001]
