objects:
  - id: cyl1
    type: cylinder
    position: [0.55, -0.4, 0.22]
    dimensions: [0.05, 0.44]  # radius, height

  - id: cyl2
    type: cylinder
    position: [0.7, 0.1, 0.2]
    dimensions: [0.03, 0.4]  # radius, height

  - id: cyl3
    type: cylinder
    position: [0.4, 0.40, 0.125]
    dimensions: [0.04, 0.25]  # radius, height

  - id: box1
    type: box
    position: [0.5, 0.0, 0.0025]  
    dimensions: [0.5, 1.5, 0.05]  # radius, width, height
